server:
  port: 9000
logging:
  level:
    sql: info
    org:
      springframework:
        security: INFO
  config: classpath:log4j2.xml
spring:
  datasource:
    hikari:
      username: root
      password: 000000
      jdbc-url: jdbc:mysql://localhost:3306/sora?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
      driver-class-name: com.mysql.cj.jdbc.Driver